# Generated by Django 2.2.12 on 2020-05-13 21:49

from django.db import migrations, models
import django.db.models.deletion
import django_date_extensions.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authority_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('citation_link', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('additional_research', models.TextField(blank=True)),
                ('zotero_id', models.CharField(max_length=100)),
                ('zotero_data', models.TextField(blank=True)),
                ('organisations', models.ManyToManyField(blank=True, to='authority_list.Organisation')),
                ('people', models.ManyToManyField(blank=True, to='authority_list.Person')),
                ('places', models.ManyToManyField(blank=True, to='authority_list.Place')),
                ('related_documents', models.ManyToManyField(blank=True, related_name='_document_related_documents_+', to='document.Document')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
            options={
                'db_table': 'document_keywords',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
            options={
                'db_table': 'document_files',
            },
        ),
        migrations.CreateModel(
            name='DocumentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', django_date_extensions.fields.ApproximateDateField()),
                ('date_to', django_date_extensions.fields.ApproximateDateField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
            options={
                'db_table': 'document_dates',
            },
        ),
    ]
