# Generated by Django 2.2.12 on 2020-05-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdate',
            name='event',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
