# Generated by Django 2.2.12 on 2020-05-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_documentdate_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='abstract',
            new_name='summary',
        ),
    ]
