# Generated by Django 2.2.12 on 2020-05-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_document_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTriggeringFactorKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
            options={
                'db_table': 'document_triggering_factor_keywords',
            },
        ),
    ]
