# Generated by Django 2.2.12 on 2020-05-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20200526_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='default', max_length=400),
            preserve_default=False,
        ),
    ]
