# Generated by Django 2.2.12 on 2020-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='record_type',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
