# Generated by Django 2.2.12 on 2020-05-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_document_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='item_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
