# Generated by Django 2.2.12 on 2020-05-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_document_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdate',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='document.Document'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='document.Document'),
        ),
        migrations.AlterField(
            model_name='documentkeyword',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='document.Document'),
        ),
        migrations.AlterField(
            model_name='documenttriggeringfactorkeyword',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggering_factor_keywords', to='document.Document'),
        ),
    ]
