# Generated by Django 2.2.12 on 2020-05-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_auto_20200526_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='file_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
