# Generated by Django 2.2.12 on 2020-06-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_auto_20200605_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='attachment_type',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
