# Generated by Django 2.2.12 on 2020-08-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority_list', '0006_event'),
        ('document', '0014_document_attachment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='events',
            field=models.ManyToManyField(blank=True, to='authority_list.Event'),
        ),
        migrations.DeleteModel(
            name='DocumentDate',
        ),
    ]
