# Generated by Django 2.2.12 on 2020-09-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_auto_20200806_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='file_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
