# Generated by Django 2.2.12 on 2020-05-13 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classification_categories',
            },
        ),
        migrations.CreateModel(
            name='ConsentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'consent_types',
            },
        ),
        migrations.CreateModel(
            name='ClassificationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('tag', 'tag'), ('group', 'group'), ('other', 'other')], max_length=5)),
                ('field', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadata.ClassificationCategory')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.ClassificationField')),
            ],
            options={
                'db_table': 'classification_fields',
            },
        ),
        migrations.CreateModel(
            name='DocumentConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.BooleanField(default=False)),
                ('consent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.ConsentType')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
            options={
                'db_table': 'consents',
                'unique_together': {('document', 'consent_type')},
            },
        ),
        migrations.CreateModel(
            name='ClassificationFurtherExplanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadata.ClassificationCategory')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
            options={
                'db_table': 'classification_further_explanations',
                'unique_together': {('document', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_other_text', models.TextField(blank=True)),
                ('classification_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadata.ClassificationField')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
            options={
                'db_table': 'classifications',
                'unique_together': {('document', 'classification_field')},
            },
        ),
    ]
