# Generated by Django 2.2.12 on 2020-05-26 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20200513_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificationcategory',
            options={'verbose_name': 'Classification Category', 'verbose_name_plural': 'Classification Categories'},
        ),
        migrations.AlterField(
            model_name='classification',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='document.Document'),
        ),
        migrations.AlterField(
            model_name='classificationfield',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='metadata.ClassificationField'),
        ),
        migrations.AlterField(
            model_name='classificationfurtherexplanation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='document.Document'),
        ),
        migrations.AlterField(
            model_name='documentconsent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='document.Document'),
        ),
    ]
