# Generated by Django 2.2.12 on 2020-06-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20200526_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='consenttype',
            name='group',
            field=models.CharField(default='interview', max_length=50),
        ),
        migrations.AddField(
            model_name='documentconsent',
            name='consent_text',
            field=models.TextField(blank=True),
        ),
    ]
