# Generated by Django 2.2.12 on 2020-06-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_auto_20200610_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificationcategory',
            options={'verbose_name': 'Classification category', 'verbose_name_plural': 'Classification categories'},
        ),
    ]
