# Generated by Django 2.2.12 on 2020-06-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_auto_20200610_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationfurtherexplanation',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
