# Generated by Django 2.2.12 on 2021-02-09 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_auto_20200619_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='classification_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.ClassificationField'),
        ),
    ]
