# Generated by Django 2.2.12 on 2021-05-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_auto_20210209_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationfield',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='ordering'),
        ),
    ]
