# Generated by Django 2.2.12 on 2021-05-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_classificationfield_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationfield',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
