# Generated by Django 2.2.12 on 2020-05-13 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'organisation_forms',
            },
        ),
        migrations.CreateModel(
            name='OrganisationFormScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'organisation_form_scales',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='PlaceOtherName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authority_list.Place')),
            ],
            options={
                'db_table': 'place_other_names',
            },
        ),
        migrations.CreateModel(
            name='PersonOtherName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authority_list.Person')),
            ],
            options={
                'db_table': 'people_other_names',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('acronym', models.CharField(blank=True, max_length=50)),
                ('organisation_form_text', models.TextField(blank=True)),
                ('organisation_form_scale_text', models.TextField(blank=True)),
                ('organisation_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authority_list.OrganisationForm')),
                ('organisation_form_scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authority_list.OrganisationFormScale')),
            ],
            options={
                'db_table': 'organisations',
            },
        ),
    ]
