# Generated by Django 2.2.12 on 2020-05-26 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority_list', '0002_auto_20200526_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeothername',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_names', to='authority_list.Place'),
        ),
    ]
