# Generated by Django 2.2.12 on 2020-05-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority_list', '0003_auto_20200526_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authority_list.OrganisationForm'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_form_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authority_list.OrganisationFormScale'),
        ),
    ]
