# Generated by Django 2.2.12 on 2021-05-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority_list', '0009_auto_20210510_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
