# Generated by Django 3.2.5 on 2023-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority_list', '0011_auto_20210607_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
